import json
import re
from pathlib import Path
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Optional, Tuple, Any

# In-memory cache for parsed files: path -> (mtime, size, byte_offset, stats, line_records, first_prompt)
_FILE_CACHE: Dict[str, Tuple[float, int, int, Dict[str, int], List[Tuple[Optional[datetime], int, int, int]], str]] = {}


def estimate_tokens(text: str) -> int:
    """Estimates Gemini token count using the standard ~4 chars/token heuristic."""
    if not text:
        return 0
    return max(1, round(len(text) / 4))


def parse_iso_time(ts_str: Optional[str]) -> Optional[datetime]:
    """Parses ISO timestamp strings into UTC datetime objects."""
    if not ts_str:
        return None
    try:
        ts_str = ts_str.replace("Z", "+00:00")
        return datetime.fromisoformat(ts_str)
    except Exception:
        return None


def extract_first_prompt(data: dict) -> Optional[str]:
    """Extracts a short snippet of the first user prompt to use as a human-readable session title."""
    source = str(data.get("source", "")).upper()
    step_type = str(data.get("type", "")).upper()
    if source in ("USER", "USER_EXPLICIT") or "USER" in step_type:
        content = data.get("content", "")
        if isinstance(content, str):
            clean = " ".join(content.replace("\r", " ").replace("\n", " ").split()).strip()
            if clean:
                return clean[:70] + ("..." if len(clean) > 70 else "")
    return None


def extract_line_tokens(data: dict) -> Tuple[int, int, int]:
    """Extracts (prompt_toks, thinking_toks, candidate_toks) from a single transcript line."""
    source = str(data.get("source", "")).upper()
    step_type = str(data.get("type", "")).upper()
    content = data.get("content", "")
    thinking_content = data.get("thinking", "")
    tool_calls = data.get("tool_calls", [])

    prompt_toks = 0
    thinking_toks = 0
    candidate_toks = 0

    if thinking_content:
        thinking_toks += estimate_tokens(thinking_content)

    text_pieces = []
    if isinstance(content, str):
        text_pieces.append(content)
    elif isinstance(content, (dict, list)):
        text_pieces.append(json.dumps(content))

    full_text = "\n".join(text_pieces).strip()
    if full_text:
        thought_matches = re.findall(r"<(?:thought|thinking)>(.*?)</(?:thought|thinking)>", full_text, flags=re.DOTALL)
        for thought in thought_matches:
            thinking_toks += estimate_tokens(thought)

        cleaned_text = re.sub(r"<(?:thought|thinking)>.*?</(?:thought|thinking)>", "", full_text, flags=re.DOTALL).strip()
        tokens = estimate_tokens(cleaned_text)

        if step_type == "PLANNER_RESPONSE":
            candidate_toks += tokens
        elif step_type in ("USER_INPUT", "CHECKPOINT", "SYSTEM_INSTRUCTIONS") or source in ("USER", "USER_EXPLICIT", "SYSTEM"):
            prompt_toks += tokens
        elif step_type == "GENERIC":
            # Tool execution output returned from environment into the model's context
            prompt_toks += tokens
        elif source == "MODEL":
            candidate_toks += tokens
        else:
            prompt_toks += tokens

    if tool_calls:
        # Tool call invocations generated by the model are candidate/output tokens
        candidate_toks += estimate_tokens(json.dumps(tool_calls))

    return prompt_toks, thinking_toks, candidate_toks


def parse_transcript_file_cached(file_path: Any) -> Tuple[Dict[str, int], List[Tuple[Optional[datetime], int, int, int]], str]:
    """
    Parses a transcript file incrementally with caching based on file modification time and byte offset.
    Only parses newly appended lines on updates for lightning-fast 0.0% CPU overhead.
    """
    if not file_path:
        return {"prompt": 0, "candidates": 0, "thinking": 0}, [], ""
    file_path = Path(file_path)
    file_key = str(file_path.resolve())
    try:
        stat = file_path.stat()
        mtime, size = stat.st_mtime, stat.st_size
    except (OSError, ValueError):
        return {"prompt": 0, "candidates": 0, "thinking": 0}, [], ""

    cached_mtime, cached_size, cached_offset = 0.0, 0, 0
    stats = {"prompt": 0, "candidates": 0, "thinking": 0}
    line_records: List[Tuple[Optional[datetime], int, int, int]] = []
    first_prompt = ""

    if file_key in _FILE_CACHE:
        cached_mtime, cached_size, cached_offset, cached_stats, cached_records, cached_prompt = _FILE_CACHE[file_key]
        if cached_mtime == mtime and cached_size == size:
            return cached_stats.copy(), list(cached_records), cached_prompt
        # If file grew and offset is valid, incrementally read new bytes
        if size >= cached_offset and cached_offset > 0:
            stats = cached_stats.copy()
            line_records = list(cached_records)
            first_prompt = cached_prompt
        else:
            cached_offset = 0

    new_offset = cached_offset
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            if cached_offset > 0:
                f.seek(cached_offset)
            for line in f:
                line_str = line.strip()
                if not line_str:
                    continue
                try:
                    data = json.loads(line_str)
                    if isinstance(data, dict):
                        if not first_prompt:
                            fp = extract_first_prompt(data)
                            if fp:
                                first_prompt = fp
                        ts = parse_iso_time(data.get("created_at"))
                        p, th, c = extract_line_tokens(data)
                        stats["prompt"] += p
                        stats["thinking"] += th
                        stats["candidates"] += c
                        line_records.append((ts, p, th, c))
                except json.JSONDecodeError:
                    continue
            new_offset = f.tell()
    except Exception:
        pass

    # Prune old cache entries if cache reaches maximum limit
    if len(_FILE_CACHE) >= 200 and file_key not in _FILE_CACHE:
        oldest_keys = list(_FILE_CACHE.keys())[:50]
        for k in oldest_keys:
            _FILE_CACHE.pop(k, None)

    _FILE_CACHE[file_key] = (mtime, size, new_offset, stats.copy(), line_records, first_prompt)
    return stats, line_records, first_prompt


def calculate_window_tracker(line_records: List[Tuple[Optional[datetime], int, int, int]], ref_time: Optional[datetime] = None) -> Dict[str, Any]:
    """Calculates 5h, 7d, and short-window burn velocity breakdowns from parsed line records."""
    now = ref_time if ref_time is not None else datetime.now(timezone.utc)
    if now.tzinfo is None:
        now = now.replace(tzinfo=timezone.utc)

    from datetime import timedelta
    cutoff = now - timedelta(days=7, hours=1)
    line_records = [r for r in line_records if r[0] is None or r[0] >= cutoff]

    window_tracker = {
        "tokens_5h": 0,
        "prompt_5h": 0,
        "thinking_5h": 0,
        "candidates_5h": 0,
        "oldest_5h_time": None,

        "tokens_7d": 0,
        "prompt_7d": 0,
        "thinking_7d": 0,
        "candidates_7d": 0,
        "oldest_7d_time": None,

        "tokens_15m": 0,
        "tokens_1h": 0,
    }

    fifteen_mins_ago = now - timedelta(minutes=15)
    one_hour_ago = now - timedelta(hours=1)
    five_hours_ago = now - timedelta(hours=5)
    seven_days_ago = now - timedelta(days=7)

    for ts, p, th, c in line_records:
        total_line = p + th + c
        if total_line <= 0 or ts is None:
            continue

        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)

        # 15-Min & 1-Hour Burn Velocity
        if ts >= fifteen_mins_ago:
            window_tracker["tokens_15m"] += total_line
        if ts >= one_hour_ago:
            window_tracker["tokens_1h"] += total_line

        # 5-Hour Window
        if ts >= five_hours_ago:
            window_tracker["tokens_5h"] += total_line
            window_tracker["prompt_5h"] += p
            window_tracker["thinking_5h"] += th
            window_tracker["candidates_5h"] += c
            if window_tracker["oldest_5h_time"] is None or ts < window_tracker["oldest_5h_time"]:
                window_tracker["oldest_5h_time"] = ts

        # 7-Day Window
        if ts >= seven_days_ago:
            window_tracker["tokens_7d"] += total_line
            window_tracker["prompt_7d"] += p
            window_tracker["thinking_7d"] += th
            window_tracker["candidates_7d"] += c
            if window_tracker["oldest_7d_time"] is None or ts < window_tracker["oldest_7d_time"]:
                window_tracker["oldest_7d_time"] = ts

    return window_tracker


def format_recovery_info(window_tracker: Dict[str, Any], ref_time: Optional[datetime] = None) -> Dict[str, Any]:
    """Formats human-readable recovery info, percentages, countdowns, and window-scoped token breakdowns."""
    now = ref_time if ref_time is not None else datetime.now(timezone.utc)
    if now.tzinfo is None:
        now = now.replace(tzinfo=timezone.utc)

    # 5-Hour Window formatting
    reset_5h_str = "No recent usage"
    pct_5h = 0.0
    secs_5h = 0
    recovery_5h_dt = None

    if window_tracker["oldest_5h_time"]:
        oldest_5h = window_tracker["oldest_5h_time"]
        if oldest_5h.tzinfo is None:
            oldest_5h = oldest_5h.replace(tzinfo=timezone.utc)
        recovery_5h_dt = oldest_5h + timedelta(hours=5)
        secs_5h = max(0, int((recovery_5h_dt - now).total_seconds()))
        pct_5h = (secs_5h / (5 * 3600)) * 100
        mins_remaining = secs_5h // 60
        hours = mins_remaining // 60
        mins = mins_remaining % 60
        if secs_5h > 0:
            reset_5h_str = f"in {hours}h {mins:02d}m ({pct_5h:.1f}% remaining)"
        else:
            reset_5h_str = "Fully recovered"

    # 7-Day Window formatting
    reset_7d_str = "No weekly usage"
    pct_7d = 0.0
    secs_7d = 0
    recovery_7d_dt = None

    if window_tracker["oldest_7d_time"]:
        oldest_7d = window_tracker["oldest_7d_time"]
        if oldest_7d.tzinfo is None:
            oldest_7d = oldest_7d.replace(tzinfo=timezone.utc)
        recovery_7d_dt = oldest_7d + timedelta(days=7)
        secs_7d = max(0, int((recovery_7d_dt - now).total_seconds()))
        pct_7d = (secs_7d / (7 * 86400)) * 100
        days_7d = secs_7d // 86400
        hours_7d = (secs_7d % 86400) // 3600
        mins_7d = (secs_7d % 3600) // 60
        if secs_7d > 0:
            if days_7d > 0:
                reset_7d_str = f"in {days_7d}d {hours_7d}h {mins_7d:02d}m ({pct_7d:.1f}% remaining)"
            else:
                reset_7d_str = f"in {hours_7d}h {mins_7d:02d}m ({pct_7d:.1f}% remaining)"
        else:
            reset_7d_str = "Fully recovered"

    toks_15m = window_tracker.get("tokens_15m", 0)
    toks_1h = window_tracker.get("tokens_1h", 0)
    burn_rate_hr = toks_15m * 4 if toks_15m > 0 else toks_1h
    burn_rate_str = f"{burn_rate_hr:,} tok/hr" if burn_rate_hr > 0 else "Idle"

    return {
        "tokens_15m": toks_15m,
        "tokens_1h": toks_1h,
        "burn_rate_hr": burn_rate_hr,
        "burn_rate_str": burn_rate_str,

        "tokens_5h": window_tracker["tokens_5h"],
        "prompt_5h": window_tracker["prompt_5h"],
        "thinking_5h": window_tracker["thinking_5h"],
        "candidates_5h": window_tracker["candidates_5h"],
        "reset_5h_str": reset_5h_str,
        "pct_5h_remaining": pct_5h,
        "secs_5h_remaining": secs_5h,
        "recovery_5h_time": recovery_5h_dt,

        "tokens_7d": window_tracker["tokens_7d"],
        "prompt_7d": window_tracker["prompt_7d"],
        "thinking_7d": window_tracker["thinking_7d"],
        "candidates_7d": window_tracker["candidates_7d"],
        "reset_7d_str": reset_7d_str,
        "pct_7d_remaining": pct_7d,
        "secs_7d_remaining": secs_7d,
        "recovery_7d_time": recovery_7d_dt,
    }


def get_empty_session_report(session_id: str = "N/A", title: str = "", account_email: str = "") -> Dict[str, Any]:
    """Generates a zero-token report dictionary when no sessions exist or when a user has no tokens in the active session."""
    return {
        "is_all": False,
        "mode": "session",
        "session_id": session_id,
        "title": title or session_id,
        "first_prompt": title or session_id,
        "account": account_email,
        "folder": "",
        "file": "",
        "last_active": "N/A",
        "mtime": 0.0,
        "size": 0,
        "prompt": 0,
        "thinking": 0,
        "candidates": 0,
        "total": 0,
        "prompt_pct": 0.0,
        "thinking_pct": 0.0,
        "candidates_pct": 0.0,
        "tokens_15m": 0,
        "tokens_1h": 0,
        "burn_rate_hr": 0,
        "burn_rate_str": "Idle",
        "tokens_5h": 0,
        "prompt_5h": 0,
        "thinking_5h": 0,
        "candidates_5h": 0,
        "reset_5h_str": "No active session usage",
        "pct_5h_remaining": 0.0,
        "secs_5h_remaining": 0,
        "recovery_5h_time": None,
        "tokens_7d": 0,
        "prompt_7d": 0,
        "thinking_7d": 0,
        "candidates_7d": 0,
        "reset_7d_str": "No active session usage",
        "pct_7d_remaining": 0.0,
        "secs_7d_remaining": 0,
        "recovery_7d_time": None,
    }


def get_session_user_report(
    session: Optional[Dict],
    target_user: str,
    active_account: str,
    ref_time: Optional[datetime] = None
) -> Dict[str, Any]:
    """
    Generates a token report for a specific user scoped strictly to a single session.
    If the session contains tokens for this user, returns that user's token metrics.
    If the user has no tokens in this session, returns an empty zeroed report.
    """
    if not session:
        return get_empty_session_report(session_id="No Active Session", title="No Active Session")

    sid = session.get("session_id", "")
    target_clean = (target_user or "").strip().lower()
    active_clean = (active_account or "").strip().lower()

    # 1. Check if ledger has specific account_usage breakdown for this session
    try:
        from core.ledger import ledger
        ledger_sess = ledger.sessions.get(sid)
        if ledger_sess:
            acc_usage = ledger_sess.get("account_usage", {})
            if isinstance(acc_usage, dict):
                for act_k, udata in acc_usage.items():
                    k_clean = act_k.strip().lower()
                    is_default = not k_clean or k_clean in ("default", "local", "default / local account")
                    match = (
                        not target_clean
                        or (target_clean in ("active", "active user") and (k_clean == active_clean or is_default))
                        or k_clean == target_clean
                        or (target_clean in ("default", "local", "default / local account") and is_default)
                        or (target_clean == active_clean and is_default)
                        or ('@' in k_clean and target_clean == k_clean.split('@')[0])
                    )
                    if match and udata.get("total", 0) > 0:
                        p = udata.get("prompt", 0)
                        th = udata.get("thinking", 0)
                        c = udata.get("candidates", 0)
                        tot = p + th + c
                        recs = udata.get("records", [])
                        window_tracker = calculate_window_tracker(recs, ref_time=ref_time)
                        recovery = format_recovery_info(window_tracker, ref_time=ref_time)
                        fp = ledger_sess.get("first_prompt") or session.get("first_prompt") or sid
                        return {
                            "is_all": False,
                            "mode": "session",
                            "session_id": sid,
                            "title": fp,
                            "first_prompt": fp,
                            "account": act_k,
                            "folder": str(session.get("folder", "")),
                            "file": str(session.get("file", "")),
                            "last_active": session.get("last_active_str", "Unknown"),
                            "mtime": session.get("mtime", 0),
                            "size": session.get("size", 0),
                            "prompt": p,
                            "thinking": th,
                            "candidates": c,
                            "total": tot,
                            "prompt_pct": (p / tot * 100) if tot > 0 else 0.0,
                            "thinking_pct": (th / tot * 100) if tot > 0 else 0.0,
                            "candidates_pct": (c / tot * 100) if tot > 0 else 0.0,
                            **recovery,
                        }
    except Exception:
        pass

    # 2. Fallback to session-level account matching
    sess_acc = session.get("account", "").strip()
    if not sess_acc or sess_acc in ("Default", "Local", "None", "Unassigned"):
        try:
            from core.ledger import ledger
            locked_acc = ledger.get_session_account(sid)
            if locked_acc:
                sess_acc = locked_acc
        except Exception:
            pass

    if not sess_acc:
        sess_acc = active_account or "Default"

    # Determine match: 'active' matches the active_account or default/local
    is_match = False
    if target_clean in ("active", "active user"):
        if sess_acc.lower() == active_clean or sess_acc in ("Default", "Local", ""):
            is_match = True
    elif target_clean:
        if sess_acc.lower() == target_clean:
            is_match = True
        elif sess_acc in ("Default", "Local", "") and target_clean == active_clean:
            is_match = True
        elif '@' in sess_acc and target_clean == sess_acc.split('@')[0].lower():
            is_match = True

    if is_match:
        return get_single_session_report(session, ref_time=ref_time, account_email=target_user)
    else:
        return get_empty_session_report(
            session_id=session.get("session_id", "N/A"),
            title=session.get("first_prompt") or session.get("session_id", "N/A"),
            account_email=target_user
        )


def get_single_session_report(session: Dict, ref_time: Optional[datetime] = None, account_email: str = "") -> Dict[str, Any]:
    """Generates complete token analysis and rate limit stats for a single session."""
    stats, records, first_prompt = parse_transcript_file_cached(session["file"])
    window_tracker = calculate_window_tracker(records, ref_time=ref_time)
    recovery = format_recovery_info(window_tracker, ref_time=ref_time)

    prompt = stats["prompt"]
    thinking = stats["thinking"]
    candidates = stats["candidates"]
    total = prompt + thinking + candidates

    prompt_pct = (prompt / total * 100) if total > 0 else 0.0
    thinking_pct = (thinking / total * 100) if total > 0 else 0.0
    candidates_pct = (candidates / total * 100) if total > 0 else 0.0

    # Sync into in-memory ledger
    try:
        from core.ledger import ledger
        from core.account_manager import is_valid_account_email
        force_acc = bool(account_email and is_valid_account_email(account_email))
        ledger.update_session(
            session_id=session.get("session_id", "unknown"),
            account_email=account_email or "Default",
            stats=stats,
            line_records=records,
            first_prompt=first_prompt,
            last_active=session.get("last_active_str", "Unknown"),
            mtime=session.get("mtime", 0.0),
            size=session.get("size", 0),
            force_account=force_acc
        )
    except Exception:
        pass

    return {
        "is_all": False,
        "mode": "session",
        "session_id": session.get("session_id", "unknown"),
        "title": first_prompt or session.get("session_id", "unknown"),
        "first_prompt": first_prompt,
        "folder": str(session.get("folder", "")),
        "file": str(session.get("file", "")),
        "last_active": session.get("last_active_str", "Unknown"),
        "mtime": session.get("mtime", 0),
        "size": session.get("size", 0),
        "prompt": prompt,
        "thinking": thinking,
        "candidates": candidates,
        "total": total,
        "prompt_pct": prompt_pct,
        "thinking_pct": thinking_pct,
        "candidates_pct": candidates_pct,
        **recovery,
    }


def get_active_account_report(account_email: str, sessions: Optional[List[Dict]] = None, ref_time: Optional[datetime] = None) -> Dict[str, Any]:
    """Generates rolling rate limit stats strictly for the active Google account from the in-memory ledger."""
    try:
        from core.ledger import ledger
        # If sessions provided, ensure they are registered in ledger
        if sessions:
            for s in sessions:
                stats, records, fp = parse_transcript_file_cached(s["file"])
                ledger.update_session(
                    session_id=s.get("session_id", "unknown"),
                    account_email=account_email or "Default",
                    stats=stats,
                    line_records=records,
                    first_prompt=fp,
                    last_active=s.get("last_active_str", "Unknown"),
                    mtime=s.get("mtime", 0.0),
                    size=s.get("size", 0)
                )
        return ledger.get_account_report(account_email=account_email, ref_time=ref_time)
    except Exception:
        return get_all_sessions_report(sessions or [], ref_time=ref_time)


def get_all_sessions_report(sessions: List[Dict], ref_time: Optional[datetime] = None) -> Dict[str, Any]:
    """Generates cumulative token analysis and rate limit stats across all sessions and syncs to ledger."""
    total_prompt = 0
    total_thinking = 0
    total_candidates = 0
    all_records: List[Tuple[Optional[datetime], int, int, int]] = []
    active_sessions_count = 0

    try:
        from core.ledger import ledger
        from core.account_manager import get_active_google_account
        active_acc = get_active_google_account() or "Default"
    except Exception:
        ledger = None
        active_acc = "Default"

    for idx, s in enumerate(sessions):
        stats, records, fp = parse_transcript_file_cached(s["file"])
        s_total = sum(stats.values())
        if s_total > 0:
            total_prompt += stats["prompt"]
            total_thinking += stats["thinking"]
            total_candidates += stats["candidates"]
            all_records.extend(records)
            active_sessions_count += 1

        if ledger:
            sid = s.get("session_id", "unknown")
            existing_acc = ledger.get_session_account(sid)
            if idx == 0 and active_acc and active_acc not in ("Default", "Local"):
                sess_acc = active_acc
                force_acc = True
            elif not existing_acc or existing_acc in ("Default", "Local", "None", "Unassigned"):
                sess_acc = active_acc
                force_acc = False
            else:
                sess_acc = existing_acc
                force_acc = False
            ledger.update_session(
                session_id=sid,
                account_email=sess_acc,
                stats=stats,
                line_records=records,
                first_prompt=fp,
                last_active=s.get("last_active_str", "Unknown"),
                mtime=s.get("mtime", 0.0),
                size=s.get("size", 0),
                folder_path=str(s.get("folder", "")),
                file_path=str(s.get("file", "")),
                force_account=force_acc
            )
            s["tokens"] = s_total
            s["account"] = sess_acc

    grand_total = total_prompt + total_thinking + total_candidates
    window_tracker = calculate_window_tracker(all_records, ref_time=ref_time)
    recovery = format_recovery_info(window_tracker, ref_time=ref_time)

    prompt_pct = (total_prompt / grand_total * 100) if grand_total > 0 else 0.0
    thinking_pct = (total_thinking / grand_total * 100) if grand_total > 0 else 0.0
    candidates_pct = (total_candidates / grand_total * 100) if grand_total > 0 else 0.0

    return {
        "is_all": True,
        "mode": "device",
        "session_id": f"All Sessions ({active_sessions_count} active)",
        "unique_sessions_count": active_sessions_count,
        "total_sessions_found": len(sessions),
        "prompt": total_prompt,
        "thinking": total_thinking,
        "candidates": total_candidates,
        "total": grand_total,
        "prompt_pct": prompt_pct,
        "thinking_pct": thinking_pct,
        "candidates_pct": candidates_pct,
        **recovery,
    }
